heat_template_version: 2014-10-16

description: >
  This is an example showing how you can do firstboot configuration
  of the nodes via cloud-init.  To enable this, replace the default
  mapping of OS::TripleO::NodeUserData in ../overcloud_resource_registry*

parameters:
  ComputeKernelArgs:
    description: >
      Space seprated list of Kernel args to be update to grub.
      The given args will be appended to existing args of GRUB_CMDLINE_LINUX in file /etc/default/grub
      Example: "intel_iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=1"
    type: string
    default: ""
  ComputeHostnameFormat:
    type: string
    default: ""
  HostCpusList:
    description: >
      A list or range of physical CPU cores to be tuned.
      The given args will be appended to the tuned cpu-partitioning profile.
      Ex. HostCpusList: '4-12' will tune cores from 4-12
    type: string
    default: ""

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: boot_config}
      - config: {get_resource: compute_kernel_args}

  boot_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        yum_repos:
          # Overcloud images deployed without any repos.
          # In order to install required tuned profile and activate it, we should create relevant repos.
          internal-rhel-7-server-rpms:
            name: Red Hat Enterprise Linux 7 Server (RPMs, internal)
            baseurl: http://10.87.29.184/repo/rhel-7-server-rpms/
            enabled: 1
            gpgcheck: 0
          internal-rhel-7-server-openstack-10-rpms:
            name: Red Hat OpenStack Platform 10 for RHEL 7 (RPMs, internal)
            baseurl: http://10.87.29.184/repo/rhel-7-server-openstack-10-rpms/
            enabled: 1
            gpgcheck: 0
          openvswitch-2.6:
            name: Open vSwitch 2.6
            baseurl: http://10.87.29.184/repo/openvswitch-2.6/
            enabled: 1
            gpgcheck: 0

  # Verify the logs on /var/log/cloud-init.log on the overcloud node
  compute_kernel_args:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          template: |
            #!/bin/bash
            set -x
            systemctl stop NetworkManager.service 
            systemctl disable NetworkManager.service
            echo -e "r00tme\nr00tme" | (passwd --stdin root)
            sed -i s/SELINUX=enforcing/SELINUX=disable/ /etc/sysconfig/selinux

outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
	
